# Auto-Batched Joint Distributions: A Gentle Tutorial

##### Copyright 2020 The TensorFlow Authors.

Licensed under the Apache License, Version 2.0 (the "License");

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License"); { display-mode: "form" }
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/probability/examples/Modeling_with_JointDistribution"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/probability/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

### Introduction

TensorFlow Probability (TFP) offers a number of `JointDistribution` abstractions that make probabilistic inference easier by allowing a user to easily express a probabilistic graphical model in a near-mathematical form; the abstraction generates methods for sampling from the model and evaluating the log probability of samples from the model. In this tutorial, we review "autobatched" variants, which were developed after the original `JointDistribution` abstractions. Relative to the original, non-autobatched abstractions, the autobatched versions are simpler to use and more ergonomic, allowing many models to be expressed with less boilerplate. In this colab, we explore a simple model in (perhaps tedious) detail, making clear the problems autobatching solves, and (hopefully) teaching the reader more about TFP shape concepts along the way.

Prior to the introduction of autobatching, there were a few different variants of `JointDistribution`, corresponding to different syntactic styles for expressing probabilistic models: `JointDistributionSequential`, `JointDistributionNamed`, and`JointDistributionCoroutine`. Auobatching exists as a mixin, so we now have `AutoBatched` variants of all of these. In this tutorial, we explore the differences between `JointDistributionSequential` and `JointDistributionSequentialAutoBatched`; however, everything we do here is applicable to the other variants with essentially no changes.


### Dependencies & Prerequisites


In [2]:
#@title Import and set ups{ display-mode: "form" }

import functools
import numpy as np

import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()

import tensorflow_probability as tfp

tfd = tfp.distributions

### Prerequisite: A Bayesian Regression Problem

We'll consider a very simple Bayesian regression scenario:
\begin{align*}
m & \sim \text{Normal}(0, 1) \\
b & \sim \text{Normal}(0, 1) \\
Y & \sim \text{Normal}(mX + b, 1)
\end{align*}

In this model, `m` and `b` are drawn from standard normals, and the observations `Y` are drawn from a normal distribution whose mean depends on the random variables `m` and `b`, and some (nonrandom, known) covariates `X`. (For simplicity, in this example, we assume the scale of all random variables is known.)

To perform inference in this model, we'd need to know both the covariates `X` and the observations `Y`, but for the purposes of this tutorial, we'll only need `X`, so we define a simple dummy `X`:

In [3]:
X = np.arange(7)
X

array([0, 1, 2, 3, 4, 5, 6])

### Desiderata

In probabilistic inference, we often want to perform two basic operations:
- `sample`: Drawing samples from the model.
- `log_prob`: Computing the log probability of a sample from the model.

The key contribution of TFP's `JointDistribution` abstractions (as well as of many other approaches to probabilistic programming) is to allow users to write a model *once* and have access to both `sample` and `log_prob` computations.

Noting that we have 7 points in our data set (`X.shape = (7,)`), we can now state the desiderata for an excellent `JointDistribution`:

* `sample()` should produce a list of `Tensors` having shape `[(), (), (7,)`], corresponding to the scalar slope, scalar bias, and vector observations, respectively.
* `log_prob(sample())` should produce a scalar: the log probability of a particular slope, bias, and observations.
* `sample([5, 3])` should produce a list of `Tensors` having shape `[(5, 3), (5, 3), (5, 3, 7)]`, representing a `(5, 3)`-*batch* of samples from the model.
* `log_prob(sample([5, 3]))` should produce a `Tensor` with shape (5, 3).

We'll now look at a succession of `JointDistribution` models, see how to achieve the above desiderata, and hopefully learn a little more about TFP shapes along the way. 

Spoiler alert: The approach that satisfies the above  desiderata without added boilerplate is [autobatching](#scrollTo=_h7sJ2bkfOS7). 

### First Attempt; `JointDistributionSequential`

In [4]:
jds = tfd.JointDistributionSequential([
    tfd.Normal(loc=0., scale=1.),   # m
    tfd.Normal(loc=0., scale=1.),   # b
    lambda b, m: tfd.Normal(loc=m*X + b, scale=1.) # Y
])

This is more or less a direct translation of the model into code. The slope `m` and bias `b` are straightforward. `Y` is defined using a `lambda`-function: the general pattern is that a `lambda`-function of $k$ arguments in a `JointDistributionSequential` (JDS) uses the previous $k$ distributions in the model. Note the "reverse" order.

We'll call `sample_distributions`, which returns both a sample *and* the underlying "sub-distributions" that were used to generate the sample. (We could have produced just the sample by calling `sample`; later in the tutorial it will be convenient to have the distributions as well.) The sample we produce is fine:

In [5]:
dists, s = jds.sample_distributions()
s

[<tf.Tensor: shape=(), dtype=float32, numpy=0.08079692>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.5032883>,
 <tf.Tensor: shape=(7,), dtype=float32, numpy=
 array([-1.906176  ,  0.53724945, -0.30291188, -0.86593336, -0.00641394,
        -0.58248115, -2.907504  ], dtype=float32)>]

But `log_prob` produces a result with an undesired shape:

In [6]:
jds.log_prob(s)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-3.9711766, -5.8103094, -4.429552 , -3.9680157, -4.578788 ,
       -4.02357  , -5.674173 ], dtype=float32)>

And multiple sampling doesn't work:

In [7]:
try:
  jds.sample([5, 3])
except tf.errors.InvalidArgumentError as e:
  print(e)

Incompatible shapes: [5,3] vs. [7] [Op:Mul]


Let's try to understand what's going wrong.

### A Brief Review: Batch and Event Shape

In TFP, an ordinary (not a `JointDistribution`) probability distribution has an *event shape* and a *batch shape*, and understanding the difference is crucial to effective use of TFP:

* Event shape describes the shape of a single draw from the distribution; the draw may be dependent across dimensions. For scalar distributions, the event shape is []. For a 5-dimensional MultivariateNormal, the event shape is [5].
* Batch shape describes independent, not identically distributed draws, aka a "batch" of distributions. Representing a batch of distributions in a single Python object is one of the key ways TFP achieves efficiency at scale.

For our purposes, a critical fact to keep in mind is that if we call `log_prob` on a single sample from a distribution, the result will always have a shape that matches (i.e., has as rightmost dimensions) the *batch* shape.

For a more in-depth discussion of shapes, see [the "Undersanding TensorFlow Distributions Shapes" tutorial](https://www.tensorflow.org/probability/examples/Understanding_TensorFlow_Distributions_Shapes).


### Why Doesn't `log_prob(sample())` Produce a Scalar? 

Let's use our knowledge of batch and event shape to explore what's happening with `log_prob(sample())`. Here's our sample again:

In [8]:
s

[<tf.Tensor: shape=(), dtype=float32, numpy=0.08079692>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.5032883>,
 <tf.Tensor: shape=(7,), dtype=float32, numpy=
 array([-1.906176  ,  0.53724945, -0.30291188, -0.86593336, -0.00641394,
        -0.58248115, -2.907504  ], dtype=float32)>]

And here are our distributions:

In [9]:
dists

[<tfp.distributions.Normal 'Normal' batch_shape=[] event_shape=[] dtype=float32>,
 <tfp.distributions.Normal 'Normal' batch_shape=[] event_shape=[] dtype=float32>,
 <tfp.distributions.Normal 'JointDistributionSequential_sample_distributions_Normal' batch_shape=[7] event_shape=[] dtype=float32>]

The log probability is computed by summing the log probabilities of the sub-distributions at the (matched) elements of the parts:

In [10]:
log_prob_parts = [dist.log_prob(ss) for (dist, ss) in zip(dists, s)]
log_prob_parts

[<tf.Tensor: shape=(), dtype=float32, numpy=-0.9222026>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.0488763>,
 <tf.Tensor: shape=(7,), dtype=float32, numpy=
 array([-1.0000978 , -2.8392305 , -1.4584732 , -0.99693686, -1.6077087 ,
        -1.0524913 , -2.703094  ], dtype=float32)>]

In [11]:
np.sum(log_prob_parts) - jds.log_prob(s)

<tf.Tensor: shape=(7,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

So, one level of explanation is that the log probability calculation is returning a 7-Tensor because the third subcomponent of `log_prob_parts` is a 7-Tensor. But why?

Well, we see that the last element of `dists`, which corresponds to our distribution over `Y` in the mathematial formulation, has a `batch_shape` of `[7]`. In other words, our distribution over `Y` is a batch of 7 independent normals (with different means and, in this case, the same scale).

We now understand what's wrong: in JDS, the distribution over `Y` has `batch_shape=[7]`, a sample from the JDS represents scalars for `m` and `b` and a "batch" of 7 independent normals. and `log_prob` computes 7 separate log-probabilities, each of which represents the log probability of drawing `m` and `b` and a single observation `Y[i]` at some `X[i]`.

### Fixing `log_prob(sample())` with `Independent`

Recall that `dists[2]` has `event_shape=[]` and `batch_shape=[7]`:

In [12]:
dists[2]

<tfp.distributions.Normal 'JointDistributionSequential_sample_distributions_Normal' batch_shape=[7] event_shape=[] dtype=float32>

By using TFP's `Independent` metadistribution, which converts batch dimensions to event dimensions, we can convert this into a distribution with `event_shape=[7]` and `batch_shape=[]` (we'll rename it `y_dist_i` because it's a distribution on `Y`, with the `_i` standing in for our `Independent` wrapping): 

In [13]:
y_dist_i = tfd.Independent(dists[2], reinterpreted_batch_ndims=1)
y_dist_i

<tfp.distributions.Independent 'IndependentJointDistributionSequential_sample_distributions_Normal' batch_shape=[] event_shape=[7] dtype=float32>

Now, the `log_prob` of a 7-vector is a scalar:

In [14]:
y_dist_i.log_prob(s[2])

<tf.Tensor: shape=(), dtype=float32, numpy=-11.658031>

Under the covers, `Independent` sums over the batch:

In [15]:
y_dist_i.log_prob(s[2]) - tf.reduce_sum(dists[2].log_prob(s[2]))

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

And indeed, we can use this to construct a new `jds_i` (the `i` again stands for `Independent`) where `log_prob` returns a scalar:

In [16]:
jds_i = tfd.JointDistributionSequential([
    tfd.Normal(loc=0., scale=1.),   # m
    tfd.Normal(loc=0., scale=1.),   # b
    lambda b, m: tfd.Independent(   # Y
        tfd.Normal(loc=m*X + b, scale=1.),
        reinterpreted_batch_ndims=1)
])

jds_i.log_prob(s)

<tf.Tensor: shape=(), dtype=float32, numpy=-14.62911>

A couple notes:
- `jds_i.log_prob(s)` is *not* the same as `tf.reduce_sum(jds.log_prob(s))`. The former produces the "correct" log probability of the joint distribution. The latter sums over a 7-Tensor, each element of which is the sum of the log probability of `m`, `b`, and a single element of the log probability of `Y`, so it overcounts `m` and `b`. (`log_prob(m) + log_prob(b) + log_prob(Y)` returns a result rather than throwing an exception because TFP follows TF and NumPy's broadcasting rules; adding a scalar to a vector produces a vector-sized result.)
- In this particular case, we could have solved the problem and achieved the same result using `MultivariateNormalDiag` instead of `Independent(Normal(...))`. `MultivariateNormalDiag` is a vector-valued distribution (i.e., it already has vector event-shape). Indeeed `MultivariateNormalDiag` could be (but isn't) implemented as a composition of `Independent` and `Normal`. It's worthwhile to remember that given a vector `V`, samples from `n1 = Normal(loc=V)`, and `n2 = MultivariateNormalDiag(loc=V)` are indistinguishable; the difference beween these distributions is that `n1.log_prob(n1.sample())` is a vector and `n2.log_prob(n2.sample())` is a scalar.

### Multiple Samples?

Drawing multiple samples still doesn't work:

In [17]:
try:
  jds_i.sample([5, 3])
except tf.errors.InvalidArgumentError as e:
  print(e)

Incompatible shapes: [5,3] vs. [7] [Op:Mul]


Let's think about why. When we call `jds_i.sample([5, 3])`, we'll first draw samples for `m` and `b`, each with shape `(5, 3)`. Next, we're going to try to construct a `Normal` distribution via:
```
tfd.Normal(loc=m*X + b, scale=1.)
```

But if `m` has shape `(5, 3)` and `X` has shape `7`, we can't multiply them together, and indeed this is the error we're hitting:

In [18]:
m = tfd.Normal(0., 1.).sample([5, 3])
try:
  m * X
except tf.errors.InvalidArgumentError as e:
  print(e)

Incompatible shapes: [5,3] vs. [7] [Op:Mul]


To resolve this issue, let's think about what properties the distribution over `Y` has to have. If we've called `jds_i.sample([5, 3])`, then we know `m` and `b` will both have shape `(5, 3)`. What shape should a call to `sample` on the `Y` distribution produce? The obvious answer is `(5, 3, 7)`: for each batch point, we want a sample with the same size as `X`. We can achieve this by using TensorFlow's broadcasting capabilities, adding extra dimensions:

In [19]:
m[..., tf.newaxis].shape

TensorShape([5, 3, 1])

In [20]:
(m[..., tf.newaxis] * X).shape

TensorShape([5, 3, 7])

Adding an axis to both `m` and `b`, we can define a new JDS that supports multiple samples:

In [21]:
jds_ia = tfd.JointDistributionSequential([
    tfd.Normal(loc=0., scale=1.),   # m
    tfd.Normal(loc=0., scale=1.),   # b
    lambda b, m: tfd.Independent(   # Y
        tfd.Normal(loc=m[..., tf.newaxis]*X + b[..., tf.newaxis], scale=1.),
        reinterpreted_batch_ndims=1)
])

ss = jds_ia.sample([5, 3])
ss

[<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[-1.0641694 ,  0.88205844, -0.3132895 ],
        [ 0.7708484 , -0.08183189, -0.543864  ],
        [-0.46075284, -1.8269578 ,  0.30572248],
        [-1.4730763 , -1.749881  , -0.18791775],
        [-1.1432608 , -0.03570032, -0.47378683]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[-0.05995331,  0.4670131 ,  0.39853612],
        [-0.50897926,  0.55372673, -0.44930768],
        [ 2.12264   , -0.8941609 , -0.22456498],
        [-0.28325766, -0.6039566 , -0.7982028 ],
        [ 1.6194319 , -1.5981796 , -1.0267515 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3, 7), dtype=float32, numpy=
 array([[[ 1.23666501e+00, -2.72573185e+00, -1.06902647e+00,
          -3.99592471e+00, -5.51451778e+00, -4.81725502e+00,
          -5.56694984e+00],
         [ 4.49036419e-01,  8.42256904e-01,  1.65697992e+00,
           2.83218813e+00,  2.02821064e+00,  5.30640173e+00,
           7.88480282e+00],
         [ 1.04598761e-0

In [22]:
jds_ia.log_prob(ss)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-13.1261215, -13.386831 , -14.021704 ],
       [-15.311695 , -11.299437 , -13.955756 ],
       [-11.30703  , -14.554242 , -12.285254 ],
       [-13.204155 , -15.515974 , -11.195538 ],
       [-12.403549 , -12.712912 ,  -9.4606905]], dtype=float32)>

As an extra check, we'll verify that the log probability for a single batch point matches what we had before:

In [23]:
(jds_ia.log_prob(ss)[3, 1] -
 jds_i.log_prob([ss[0][3, 1],
                 ss[1][3, 1],
                 ss[2][3, 1, :]]))

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

<a id='AutoBatching-For-The-Win'></a>
### AutoBatching For The Win


Excellent! We now have a version of JointDistribution that handles all our desiderata: `log_prob` returns a scalar thanks to the use of `tfd.Independent`, and multiple samples work now that we fixed broadcasting by adding extra axes.

What if I told you there was an easier, better way? There is, and it's called `JointDistributionSequentialAutoBatched` (JDSAB):

In [24]:
jds_ab = tfd.JointDistributionSequentialAutoBatched([
    tfd.Normal(loc=0., scale=1.),   # m
    tfd.Normal(loc=0., scale=1.),   # b
    lambda b, m: tfd.Normal(loc=m*X + b, scale=1.) # Y
])

In [25]:
jds_ab.log_prob(jds.sample())

<tf.Tensor: shape=(), dtype=float32, numpy=-10.550432>

In [26]:
ss = jds_ab.sample([5, 3])
jds_ab.log_prob(ss)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-16.063435 , -11.415724 , -13.347199 ],
       [-13.534442 , -20.753754 , -11.381274 ],
       [-10.44528  , -12.624834 , -10.739721 ],
       [-16.03442  , -13.358179 , -11.850428 ],
       [ -9.4756365, -11.457652 , -10.145042 ]], dtype=float32)>

In [27]:
jds_ab.log_prob(ss) - jds_ia.log_prob(ss)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

How does this work? While you could attempt to [read the code](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/joint_distribution_auto_batched.py#L426) for a deep understanding, we'll give a brief overview which is sufficient for most use cases:
- Recall that our first problem was that our distribution for `Y` had `batch_shape=[7]` and `event_shape=[]`, and we used `Independent` to convert the batch dimension to an event dimension. JDSAB ignores the batch shapes of component distributions; instead it treats batch shape as an overall property of the model, which is assumed to be `[]` (unless specified otherwise by setting `batch_ndims > 0`). The effect is equivalent to using tfd.Independent to convert *all* batch dimensions of component distributions into event dimensions, as we did manually above.
- Our second problem was a need to massage the shapes of `m` and `b` so that they could broadcast appropriately with `X` when creating multiple samples. With JDSAB, you write a model to generate a single sample, and we "lift" the entire model to generate multiple samples using TensorFlow's [vectorized_map](https://www.tensorflow.org/api_docs/python/tf/vectorized_map). (This feature is analagous to JAX's [vmap](https://jax.readthedocs.io/en/latest/notebooks/quickstart.html#Auto-vectorization-with-vmap).)

Exploring the batch shape issue in more detail, we can compare the batch shapes of our original "bad" joint distribution `jds`, our batch-fixed distributions `jds_i` and `jds_ia`, and our autobatched `jds_ab`:

In [28]:
jds.batch_shape

[TensorShape([]), TensorShape([]), TensorShape([7])]

In [29]:
jds_i.batch_shape

[TensorShape([]), TensorShape([]), TensorShape([])]

In [30]:
jds_ia.batch_shape

[TensorShape([]), TensorShape([]), TensorShape([])]

In [31]:
jds_ab.batch_shape

TensorShape([])

We see that the original `jds` has subdistributions with different batch shapes. `jds_i` and `jds_ia` fix this by creating subdistributions with the same (empty) batch shape. `jds_ab` has only a single (empty) batch shape.

It's worth noting that `JointDistributionSequentialAutoBatched` offers some additional generality for free. Suppose we make the covariates `X` (and, implicitly, the observations `Y`) two-dimensional:

In [32]:
X = np.arange(14).reshape((2, 7))
X

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

Our `JointDistributionSequentialAutoBatched` works with no changes (we need to redefine the model because the shape of `X` is cached by `jds_ab.log_prob`):

In [33]:
jds_ab = tfd.JointDistributionSequentialAutoBatched([
    tfd.Normal(loc=0., scale=1.),   # m
    tfd.Normal(loc=0., scale=1.),   # b
    lambda b, m: tfd.Normal(loc=m*X + b, scale=1.) # Y
])

ss = jds_ab.sample([5, 3])
ss

[<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[-1.0845535 , -1.1255777 , -0.77237695],
        [-1.2722294 ,  1.9274628 ,  0.75446165],
        [ 1.214832  ,  2.03594   ,  0.68272597],
        [-0.5651716 ,  1.6402307 ,  0.6128305 ],
        [-0.01167952,  1.2298371 , -1.2706645 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[-0.5194242 ,  0.2823965 , -0.9434134 ],
        [ 0.43568254, -0.37366644, -1.9174438 ],
        [-0.8661425 , -1.4302185 ,  0.44063085],
        [ 0.36433375, -0.38744366,  0.6491046 ],
        [ 0.91218525,  0.36210015, -0.00910723]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3, 2, 7), dtype=float32, numpy=
 array([[[[ -0.16874743,  -0.38901854,  -2.40703   ,  -5.930318  ,
            -3.416317  ,  -7.0882726 ,  -6.631361  ],
          [ -8.920654  , -10.499766  , -10.377804  , -12.9798355 ,
           -11.721172  , -14.460028  , -14.922584  ]],
 
         [[  0.50552297,  -0.9746385 ,  -2.047492  ,  -3.0749147 ,
         

In [34]:
jds_ab.log_prob(ss)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-23.592081, -20.392092, -20.310911],
       [-25.823744, -22.132751, -23.761002],
       [-21.39077 , -27.747965, -25.098429],
       [-21.14306 , -29.653296, -21.353765],
       [-24.754295, -23.107279, -20.329145]], dtype=float32)>

On the other hand, our carefully crafted `JointDistributionSequential` no longer works:

In [35]:
jds_ia = tfd.JointDistributionSequential([
    tfd.Normal(loc=0., scale=1.),   # m
    tfd.Normal(loc=0., scale=1.),   # b
    lambda b, m: tfd.Independent(   # Y
        tfd.Normal(loc=m[..., tf.newaxis]*X + b[..., tf.newaxis], scale=1.),
        reinterpreted_batch_ndims=1)
])

try:
  jds_ia.sample([5, 3])
except tf.errors.InvalidArgumentError as e:
  print(e)

Incompatible shapes: [5,3,1] vs. [2,7] [Op:Mul]


To fix this, we'd have to add a second `tf.newaxis` to both `m` and `b` match the shape, and increase `reinterpreted_batch_ndims` to 2 in the call to `Independent`. In this case, letting the auto-batching machinery handle the shape issues is shorter, easier, and more ergonomic.

Once again, we note that while this notebook explored `JointDistributionSequentialAutoBatched`, the other variants of `JointDistribution` have equivalent `AutoBatched`. (For users of  `JointDistributionCoroutine`, `JointDistributionCoroutineAutoBatched` has the additional benefit that you no longer need to specify `Root` nodes; if you've never used `JointDistributionCoroutine` you can safely ignore this statement.)

### Concluding Thoughts

In this notebook, we introduced `JointDistributionSequentialAutoBatched` and worked through a simple example in detail. Hopefully you learned something about TFP shapes and about autobatching!